Multiple parse arguments declarations
p-groarke/ns_getopt pull request #10
Opened 2017-04-30 18:19 UTC by alxarsenault

2017-04-30 18:32 UTC, Socapex commented
Gonna need a rebase (conflicts)

2017-04-30 18:54 UTC, Socapex commented
Oh and push with your email set in your git, that should add you to contributors I believe.
```
$ git config --global user.name "John Doe"
$ git config --global user.email "john@doe.org"
$ /* do your rebase */
```

Then change the last commit's author and email.
```
$ git commit --amend --author="John Doe <john@doe.org>"
```

2017-04-30 20:30 UTC, p-groarke requested changes

2017-04-30 20:30 UTC, Socapex commented on include/ns_getopt.h
> +	bool first = !arguments_are_optional;
shouldn't be negated anymore

2017-04-30 20:30 UTC, Socapex commented on include/ns_getopt.h
> +			if (argc == 1 && has_flag(option.flags, arguments_are_optional)) {
Should be negated.

2017-04-30 20:30 UTC, Socapex commented on include/ns_getopt.h
> +	if (has_flag(option.flags, flag::dont_print_help))
This is broken. Copy paste from master.

2017-04-30 20:37 UTC, alxarsenault commented on include/ns_getopt.h
> +	if (has_flag(option.flags, flag::dont_print_help))
Done.

2017-04-30 20:37 UTC, alxarsenault commented on include/ns_getopt.h
> +			if (argc == 1 && has_flag(option.flags, arguments_are_optional)) {
Done.

2017-04-30 20:38 UTC, alxarsenault commented on include/ns_getopt.h
> +	bool first = !arguments_are_optional;
Done.

2017-04-30 20:42 UTC, p-groarke approved these changes

2017-05-01 17:20 UTC, merged

2017-05-01 17:20 UTC, Socapex commented
Awesome!